import { openDB, getShopSettings } from "./db";
import { createCoupon } from "./couponService";

/* ── Helper: future expiry date string ── */
function getExpiryDate(daysFromNow) {
  const d = new Date();
  d.setDate(d.getDate() + daysFromNow);
  return d.toISOString().split("T")[0]; // "YYYY-MM-DD"
}

export async function evaluateAutoCoupon(customerId, amount) {

  if (!customerId || amount <= 0) return;

  const db = await openDB();

  const milestonesToReward = [];

  return new Promise((resolve, reject) => {

    const tx = db.transaction("customers", "readwrite");
    const store = tx.objectStore("customers");

    const getReq = store.get(customerId);

    getReq.onsuccess = () => {

      const customer = getReq.result;
      if (!customer) {
        resolve();
        return;
      }

      // Milestones: ₹5000, ₹15000, ₹50000 lifetime spend
      const milestones = [5000, 15000, 50000];

      for (const milestone of milestones) {
        if (
          (customer.lifetimeSpend || 0) >= milestone &&
          !customer[`reward_${milestone}`]
        ) {
          customer[`reward_${milestone}`] = true;
          milestonesToReward.push(milestone);
        }
      }

      store.put(customer);
    };

    tx.oncomplete = async () => {
      // Generate coupons AFTER transaction safely completes
      for (const milestone of milestonesToReward) {
        await generateRewardCoupon(customerId, milestone);
      }
      resolve();
    };

    tx.onerror = () => reject(tx.error);
  });
}

async function generateRewardCoupon(customerId, milestone) {

  const shopSettings = await getShopSettings();
  const shopId = shopSettings?.shopId;

  // Reward formula — flat ₹ discount (safe for kirana margins)
  // type: "flat" means ₹ off (not %)
  let value;
  let minPurchase;
  let title;

  if (milestone === 5000) {
    value       = 50;    // ₹50 off
    minPurchase = 300;   // on min ₹300 purchase
    title       = "🎁 Loyalty Reward – ₹50 Off";
  } else if (milestone === 15000) {
    value       = 120;   // ₹120 off
    minPurchase = 700;
    title       = "🏆 Silver Loyalty – ₹120 Off";
  } else if (milestone === 50000) {
    value       = 400;   // ₹400 off
    minPurchase = 2000;
    title       = "👑 Gold Loyalty – ₹400 Off";
  } else {
    return;
  }

  const coupon = {
    id:            crypto.randomUUID(),
    customerId,
    shopId,
    title,
    code:          "REWARD-" + milestone + "-" + Date.now(),
    type:          "flat",        // ← flat ₹ discount (not %)
    value,
    minPurchase,
    expiryDate:    getExpiryDate(90),  // valid 90 days
    expiresAt:     new Date(getExpiryDate(90)).getTime(),
    active:        true,
    used:          false,
    autoGenerated: true,
    issuedAt:      Date.now(),
    createdAt:     Date.now()
  };

  await createCoupon(coupon);
}